# Generated by Django 2.2.2 on 2020-09-30 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.CharField(max_length=20, verbose_name='班级ID')),
                ('cl_name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('cl_class_place', models.CharField(max_length=100, verbose_name='上课地点')),
                ('cl_class_data', models.CharField(max_length=20, verbose_name='上课日期')),
                ('cl_class_start_time', models.CharField(max_length=20, verbose_name='上课开始时间')),
                ('cl_class_end_time', models.CharField(max_length=20, verbose_name='上课结束时间')),
                ('cl_note', models.TextField(max_length=1000, null=True, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '班级表',
                'verbose_name_plural': '班级表',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_course_id', models.CharField(default='', max_length=20, verbose_name='课程ID')),
                ('c_section_theme', models.CharField(max_length=1000, verbose_name='小节主题')),
                ('c_level', models.CharField(max_length=10, verbose_name='难度')),
                ('c_program_design', models.CharField(max_length=1000, null=True, verbose_name='程序设计')),
                ('c_mechanical', models.CharField(max_length=1000, null=True, verbose_name='机械原理')),
                ('c_content_theme', models.CharField(max_length=500, verbose_name='内容主题')),
                ('c_scientific', models.CharField(max_length=500, null=True, verbose_name='科学原理')),
                ('c_teacher_experience', models.CharField(max_length=1000, null=True, verbose_name='教学经验')),
                ('c_classroom', models.CharField(max_length=30, verbose_name='教室')),
                ('c_child_five_theme', models.CharField(max_length=50, null=True, verbose_name='幼儿五大主题')),
                ('c_course_from', models.CharField(max_length=1000, null=True, verbose_name='课程来源')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '课程详细表',
                'verbose_name_plural': '课程详细表',
            },
        ),
        migrations.CreateModel(
            name='CourseTypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_course_id', models.CharField(default='', max_length=20, verbose_name='课程ID')),
                ('ct_course_name', models.CharField(default='', max_length=50, verbose_name='课程名称')),
                ('ct_study_age', models.CharField(default='', max_length=20, verbose_name='推荐学习年龄')),
                ('ct_equipment', models.CharField(default='', max_length=50, verbose_name='器材')),
                ('ct_note', models.CharField(default='', max_length=2000, null=True, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '课程总表',
                'verbose_name_plural': '课程总表',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='', max_length=6, verbose_name='姓名')),
                ('s_id', models.CharField(max_length=10, verbose_name='学号')),
                ('s_gender', models.BooleanField(default=False, verbose_name='性别（打勾表示男）')),
                ('s_birthday', models.DateField(default='1900-01-01', verbose_name='出生日期')),
                ('s_phone', models.CharField(default='', max_length=20, verbose_name='手机号码')),
                ('s_status', models.BooleanField(default=True, verbose_name='是否在读（打勾表示在读）')),
                ('s_into', models.DateField(default='1900-01-01', verbose_name='报名日期')),
                ('s_note', models.TextField(default='', null=True, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(default=None, max_length=10, verbose_name='姓名')),
                ('t_age', models.IntegerField(verbose_name='年龄')),
                ('t_gender', models.BooleanField(default=1, verbose_name='性别（打勾表示男）')),
                ('t_professional', models.CharField(max_length=100, null=True, verbose_name='专业')),
                ('t_school', models.CharField(max_length=200, null=True, verbose_name='毕业学校')),
                ('t_work_goal', models.CharField(max_length=100, null=True, verbose_name='工作方向')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=10, verbose_name='用户ID')),
                ('u_name', models.CharField(max_length=10, verbose_name='用户名')),
                ('u_pwd', models.CharField(max_length=10, verbose_name='密码')),
                ('u_nickname', models.CharField(max_length=10, verbose_name='昵称')),
                ('u_type', models.IntegerField(default='1', verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='StudentClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_date', models.DateField(verbose_name='上课时间')),
                ('sc_use_time', models.IntegerField(default=1, verbose_name='消耗课时')),
                ('sc_place', models.CharField(max_length=50, verbose_name='上课地点')),
                ('sc_note', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sc_bj_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.ClassInfo', verbose_name='上课班级ID')),
                ('sc_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.CourseTypeInfo', verbose_name='课程ID')),
                ('sc_section_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.CourseInfo', verbose_name='课程小节主题')),
                ('sc_teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.TeacherInfo', verbose_name='任课老师')),
            ],
            options={
                'verbose_name': '教师上课流水',
                'verbose_name_plural': '教师上课流水',
            },
        ),
        migrations.CreateModel(
            name='MoneyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_money', models.IntegerField(default='', verbose_name='金额')),
                ('m_into_date', models.DateField(default='1900-01-01', verbose_name='入账时间')),
                ('m_regular_time', models.IntegerField(default='', verbose_name='购买常规课数量')),
                ('m_special_time', models.IntegerField(default='', null=True, verbose_name='购买特殊课数量')),
                ('m_note', models.TextField(default='', max_length=1000, null=True, verbose_name='备注')),
                ('m_discount_from', models.CharField(max_length=500, null=True, verbose_name='优惠情况')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('m_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='学生学号')),
            ],
            options={
                'verbose_name': '财务表',
                'verbose_name_plural': '财务表',
            },
        ),
        migrations.AddField(
            model_name='classinfo',
            name='cl_teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.TeacherInfo', verbose_name='教师姓名'),
        ),
        migrations.CreateModel(
            name='ClassDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_note', models.CharField(max_length=1000, null=True, verbose_name='备注')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentClassInfo', verbose_name='课程名称')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentInfo', verbose_name='上课学生')),
                ('t_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.TeacherInfo', verbose_name='老师信息')),
            ],
            options={
                'verbose_name': '学生上课流水表',
                'verbose_name_plural': '学生上课流水表',
            },
        ),
    ]
