# Generated by Django 2.2.2 on 2020-09-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200930_1525'),
    ]

    operations = [
    ]
